export const SPENDING_FIELDS = [
  "Electric bills",
  "Religious Books",
  "Educational Materials",
  "Tech for Education",
  "Library Resources",
  "Building Maintenance",
  "New Construction",
  "Hygiene & Sanitation",
  "Student Food & Housing",
  "Student Aid",
  "Medical Expenses",
  "Student Supplies",
  "Teacher Training",
  "Office Supplies",
  "Transportation",
  "Community Programs",
  "Charity Support",
  "Community Education",
] as const;

export const ALL_MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;
export const YEARS_ARR = [
  "2024",
  "2025",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
] as const;
